AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False #Since i am not taking dense layer
EPOCHS: 3
CLASSES: 2
WEIGHTS: imagenet #Downloaded model is trained on imagenet dataset
LEARNING_RATE: 0.02
